version: '3.3'
services:
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: 'planner_db'
      # SQL-User
      MYSQL_USER: 'root'
      # Passwort des SQL-Nutzers
      MYSQL_PASSWORD: 'passwd'
      # Passwort für den Root-Zugriff
      MYSQL_ROOT_PASSWORD: 'passwd'
    ports:
      # <Port exposed> : < MySQL Port im container>
      - '3306:3306'
    expose:
      # Öffnet Port innerhalb des Containers
      - '3306'
      # Pfad zur persistenten Speicherung der Daten
    volumes:
      - planner_db:/var/lib/mysql
# Bezeichnung der Datenbank
volumes:
  planner_db:
